package org.dicekeys.api

//
//  DerivationRecipeTemplates.kt
//  DiceKeys
//
//  Auto-generated by recipe.ts in the DiceKeys specification TypeScript project.
//  Tue, 26 Jan 2021 11:05:00 GMT
//
import org.dicekeys.crypto.seeded.DerivationOptions

val derivationRecipeTemplates: Array<DerivationRecipe> = arrayOf(
        DerivationRecipe(DerivationOptions.Type.Password, "1Password", """{"allow":[{"host":"*.1password.com"}]}"""),
        DerivationRecipe(DerivationOptions.Type.Password, "Apple", """{"allow":[{"host":"*.apple.com"},{"host":"*.icloud.com"}],"lengthInChars":64}"""),
        DerivationRecipe(DerivationOptions.Type.Password, "Authy", """{"allow":[{"host":"*.authy.com"}]}"""),
        DerivationRecipe(DerivationOptions.Type.Password, "Bitwarden", """{"allow":[{"host":"*.bitwarden.com"}]}"""),
        DerivationRecipe(DerivationOptions.Type.Password, "Facebook", """{"allow":[{"host":"*.facebook.com"}]}"""),
        DerivationRecipe(DerivationOptions.Type.Password, "Google", """{"allow":[{"host":"*.google.com"}]}"""),
        DerivationRecipe(DerivationOptions.Type.Password, "Keeper", """{"allow":[{"host":"*.keepersecurity.com"},{"host":"*.keepersecurity.eu"}]}"""),
        DerivationRecipe(DerivationOptions.Type.Password, "LastPass", """{"allow":[{"host":"*.lastpass.com"}]}"""),
        DerivationRecipe(DerivationOptions.Type.Password, "Microsoft", """{"allow":[{"host":"*.microsoft.com"},{"host":"*.live.com"}]}""")
)
