plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.parcelize'
    id 'org.jetbrains.kotlin.plugin.serialization'
    id 'org.jetbrains.dokka'
    id 'kotlin-kapt'
}

android {
    compileSdkVersion 36

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 35
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlin {
        jvmToolchain 17
    }

    testOptions {
        unitTests {
            includeAndroidResources true
        }
    }

    namespace 'org.dicekeys.api'
    buildToolsVersion buildToolsVersion
}

dependencies {
    implementation project(':dicekey')

    implementation "com.github.dicekeys:seeded-crypto-android:$seeded_crypto"

    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$kotlinx_coroutines_version"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-core:$kotlinx_serialization_version"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:$kotlinx_serialization_version"

    implementation 'androidx.appcompat:appcompat:1.7.1'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'


}
